import{S as l,i}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const u="46793752-15e3775c3640735c851618a54",d="https://pixabay.com/api/";async function f(a){const r=`${d}?key=${u}&q=${encodeURIComponent(a)}&image_type=photo&orientation=horizontal&safesearch=true`,o=await fetch(r);if(!o.ok)throw new Error("Failed to fetch images");return(await o.json()).hits}let c=null;function m(a){const r=document.querySelector(".gallery");r.innerHTML="";const o=a.map(t=>`
      <a href="${t.largeImageURL}" class="gallery-item">
        <img src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}" class="gallery-image"/>
        <div class="info">
          <p class="article-strick" ><b class="main-word" >Likes:</b> ${t.likes}</p>
          <p class="article-strick" ><b class="main-word" >Views:</b> ${t.views}</p>
          <p class="article-strick" ><b class="main-word" >Comments:</b> ${t.comments}</p>
          <p class="article-strick" ><b class="main-word" >Downloads:</b> ${t.downloads}</p>
        </div>
      </a>`).join("");r.insertAdjacentHTML("beforeend",o),c?c.refresh():c=new l(".gallery a")}function y(){document.querySelector(".loader").style.display="block"}function p(){document.querySelector(".loader").style.display="none"}document.querySelector(".search-form").addEventListener("submit",async a=>{a.preventDefault();const r=a.target.elements.searchQuery.value.trim();if(!r){i.warning({title:"Warning",message:"Please enter a search query."});return}y();try{const o=await f(r);o.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):m(o)}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{p()}});
//# sourceMappingURL=index.js.map
