import{S as c,i}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const u="46793752-15e3775c3640735c851618a54",f="https://pixabay.com/api/";async function d(n){const r=`${f}?key=${u}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`,s=await fetch(r);if(!s.ok)throw new Error("Failed to fetch images");return(await s.json()).hits}let l=null;function m(n){const r=document.querySelector(".gallery");r.innerHTML="";const s=n.map(t=>`
      <a href="${t.largeImageURL}" class="gallery__item">
        <img src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}" class="gallery__image"/>
        <div class="info">
          <p><b>Likes:</b> ${t.likes}</p>
          <p><b>Views:</b> ${t.views}</p>
          <p><b>Comments:</b> ${t.comments}</p>
          <p><b>Downloads:</b> ${t.downloads}</p>
        </div>
      </a>`).join("");r.insertAdjacentHTML("beforeend",s),l?l.refresh():l=new c(".gallery a")}function y(){document.querySelector(".loader").style.display="block"}function p(){document.querySelector(".loader").style.display="none"}document.querySelector(".search-form").addEventListener("submit",async n=>{n.preventDefault();const r=n.target.elements.searchQuery.value.trim();if(!r){i.warning({title:"Warning",message:"Please enter a search query."});return}y();try{const s=await d(r);s.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):m(s)}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{p()}});
//# sourceMappingURL=index.js.map
